# Ignora System.out/System.err SOLO nel codice CLI
sonar.issue.ignore.multicriteria=e1

sonar.issue.ignore.multicriteria.e1.ruleKey=java:S106
sonar.issue.ignore.multicriteria.e1.resourceKey=src/main/java/controller/cli/**